DROP TABLE TMDAD16.TAG;
DROP TABLE TMDAD16.ANALYSIS_RESOURCE;
DROP TABLE TMDAD16.RESULT;
DROP TABLE TMDAD16.CHAPTER;
DROP TABLE TMDAD16.BOOK;
DROP TABLE TMDAD16.TERM_IN_THEME;
DROP TABLE TMDAD16.THEME;
DROP TABLE TMDAD16.USER;

CREATE TABLE TMDAD16.USER(
        username VARCHAR(20) PRIMARY KEY,
        password VARCHAR(20) NOT NULL
);

CREATE TABLE TMDAD16.THEME(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	themeOwner VARCHAR(20) NOT NULL,
	UNIQUE KEY (name, themeOwner),
	FOREIGN KEY (themeOwner) REFERENCES TMDAD16.USER(username)
);

CREATE TABLE TMDAD16.TERM_IN_THEME(
	term VARCHAR(30),
	theme BIGINT,
	PRIMARY KEY (term, theme),
	FOREIGN KEY (theme) REFERENCES TMDAD16.THEME(id)
);

CREATE TABLE TMDAD16.BOOK(
	id BIGINT PRIMARY KEY,
	title VARCHAR(200) NOT NULL
);

CREATE TABLE TMDAD16.CHAPTER(
	book BIGINT,
	num INT,
	chapterTitle VARCHAR(200),
	PRIMARY KEY (book, num),
	FOREIGN KEY(book) REFERENCES TMDAD16.BOOK(id)
);

CREATE TABLE TMDAD16.RESULT(
	book BIGINT,
	chapter INT,
	term VARCHAR(30),
	termCount INT NOT NULL,
	PRIMARY KEY (book, chapter, term),
	FOREIGN KEY (book, chapter) REFERENCES TMDAD16.CHAPTER(book, num)
);

CREATE TABLE TMDAD16.ANALYSIS_RESOURCE(
	resourceId BIGINT AUTO_INCREMENT PRIMARY KEY,
	book BIGINT NOT NULL,
	user VARCHAR(20) NOT NULL,
	state VARCHAR(10) NOT NULL,
	FOREIGN KEY (user) REFERENCES TMDAD16.USER(username)
);

CREATE TABLE TMDAD16.TAG(
	analysis BIGINT,
	theme VARCHAR(50),
	term VARCHAR(30),
	PRIMARY KEY (analysis, theme, term),
	FOREIGN KEY (analysis) REFERENCES TMDAD16.ANALYSIS_RESOURCE(resourceId)
);
	

